# Generated by Django 4.1.8 on 2026-07-28 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lyworkflow', '0002_workflowstep_internal_conditions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageBuild',
            fields=[
                ('id', models.CharField(default=utils.models.make_uuid, help_text='Id', max_length=100, primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=100, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=100, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=100, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('project_name', models.CharField(max_length=200, verbose_name='项目名称')),
                ('project_version', models.CharField(blank=True, max_length=50, null=True, verbose_name='项目版本')),
                ('build_type', models.CharField(choices=[('Release', 'Release'), ('Debug', 'Debug'), ('Test', 'Test')], default='Release', max_length=20, verbose_name='构建类型')),
                ('jenkins_job_name', models.CharField(max_length=200, verbose_name='Jenkins任务名称')),
                ('jenkins_build_number', models.IntegerField(blank=True, null=True, verbose_name='Jenkins构建编号')),
                ('jenkins_build_url', models.URLField(blank=True, null=True, verbose_name='Jenkins构建URL')),
                ('build_status', models.SmallIntegerField(choices=[(0, '构建中'), (1, '成功'), (2, '失败')], default=0, verbose_name='构建状态')),
                ('build_log', models.TextField(blank=True, null=True, verbose_name='构建日志')),
                ('build_params', models.JSONField(blank=True, null=True, verbose_name='构建参数')),
                ('need_delivery', models.BooleanField(default=False, verbose_name='是否需要传包')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('workflow_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='package_builds', to='lyworkflow.workflowinstance', verbose_name='关联审批流程')),
            ],
            options={
                'verbose_name': '打包构建记录',
                'verbose_name_plural': '打包构建记录',
                'db_table': 'engineering_package_build',
                'ordering': ('-create_datetime',),
            },
        ),
    ]
