# Generated by Django 4.1.8

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagebuild',
            name='build_status',
            field=models.SmallIntegerField(choices=[(0, '构建中'), (1, '成功'), (2, '失败'), (3, '未构建')], default=0, verbose_name='构建状态'),
        ),
        migrations.AddField(
            model_name='packagebuild',
            name='build_log_complete',
            field=models.BooleanField(default=False, verbose_name='构建日志是否完整'),
        ),
    ]
