# Generated by Django 4.1.8 on 2026-08-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0002_alter_packagebuild_build_status_add_build_log_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagebuild',
            name='delivery_form_data',
            field=models.JSONField(blank=True, null=True, verbose_name='发包审批表单数据'),
        ),
        migrations.AddField(
            model_name='packagebuild',
            name='delivery_workflow_status',
            field=models.SmallIntegerField(default=0, verbose_name='自动发起审批流状态'),
        ),
    ]
