# Generated by Django 4.1.8 on 2026-08-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0003_packagebuild_delivery_form_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagebuild',
            name='delivery_workflow_status',
            field=models.SmallIntegerField(choices=[(0, '未启用/待发起'), (1, '已自动发起'), (2, '自动发起失败')], default=0, verbose_name='自动发起审批流状态'),
        ),
    ]
