# Generated by Django 4.2.30 on 2026-08-13 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineering', '0004_alter_packagebuild_delivery_workflow_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagebuild',
            name='scan_build_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='扫描Jenkins构建编号'),
        ),
        migrations.AddField(
            model_name='packagebuild',
            name='scan_job_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='扫描Jenkins任务名称'),
        ),
        migrations.AddField(
            model_name='packagebuild',
            name='scan_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='包扫描状态'),
        ),
    ]
