# Generated by Django 4.1.8 on 2026-08-18 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('mysystem', '0002_alter_users_identity_alter_users_mobile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('engineering', '0005_packagebuild_scan_build_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageProjectPermission',
            fields=[
                ('id', models.CharField(default=utils.models.make_uuid, help_text='Id', max_length=100, primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=100, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=100, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=100, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('job_name', models.CharField(help_text='Jenkins任务名称', max_length=200, unique=True, verbose_name='Jenkins任务名称')),
                ('is_public', models.BooleanField(default=False, help_text='勾选后所有用户可见', verbose_name='公共可见')),
                ('remark', models.TextField(blank=True, help_text='备注', null=True, verbose_name='备注')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('visible_depts', models.ManyToManyField(blank=True, db_constraint=False, help_text='可见部门', to='mysystem.dept', verbose_name='可见部门')),
                ('visible_roles', models.ManyToManyField(blank=True, db_constraint=False, help_text='可见角色', to='mysystem.role', verbose_name='可见角色')),
                ('visible_users', models.ManyToManyField(blank=True, db_constraint=False, help_text='可见用户', related_name='visible_users_permissions', to=settings.AUTH_USER_MODEL, verbose_name='可见用户')),
            ],
            options={
                'verbose_name': '打包项目可见性授权',
                'verbose_name_plural': '打包项目可见性授权',
                'db_table': 'engineering_package_project_permission',
            },
        ),
    ]
