# Generated by Django 4.1.8 on 2026-05-20 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_datetime', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('applicant', models.CharField(max_length=100, verbose_name='申请人')),
                ('applicant_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='申请人ID')),
                ('application_type', models.CharField(choices=[('flexnet', 'FlexNet'), ('bitanswer', 'Bitanswer')], max_length=20, verbose_name='License类型')),
                ('feature', models.CharField(max_length=500, verbose_name='Feature')),
                ('customer_name', models.CharField(max_length=200, verbose_name='客户名称')),
                ('mac_address', models.CharField(max_length=100, verbose_name='MAC Address/HostID')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('quantity', models.IntegerField(default=1, verbose_name='授权数量')),
                ('json_data', models.JSONField(blank=True, null=True, verbose_name='JSON原始数据')),
                ('status', models.IntegerField(choices=[(3, '待制作'), (2, '制作中'), (1, '制作成功'), (0, '制作失败')], default=0, verbose_name='状态')),
                ('fail_reason', models.TextField(blank=True, null=True, verbose_name='失败原因')),
                ('retry_count', models.IntegerField(default=0, verbose_name='重试次数')),
                ('max_retry_count', models.IntegerField(default=3, verbose_name='最大重试次数')),
            ],
            options={
                'verbose_name': 'License申请',
                'verbose_name_plural': 'License申请',
                'db_table': 'lylicense_application',
                'ordering': ['-create_datetime'],
            },
        ),
        migrations.CreateModel(
            name='LicenseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_datetime', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('license_id', models.CharField(max_length=100, unique=True, verbose_name='License ID')),
                ('license_type', models.CharField(choices=[('flexnet', 'FlexNet'), ('bitanswer', 'Bitanswer')], max_length=20, verbose_name='类型')),
                ('file_name', models.CharField(max_length=200, verbose_name='文件名称')),
                ('file_relative_path', models.CharField(max_length=500, verbose_name='文件相对路径')),
                ('directory', models.CharField(max_length=500, verbose_name='目录')),
                ('full_path', models.CharField(max_length=500, verbose_name='完整路径')),
                ('feature', models.CharField(max_length=500, verbose_name='Feature')),
                ('vendor', models.CharField(blank=True, max_length=200, null=True, verbose_name='Vendor')),
                ('version', models.CharField(blank=True, max_length=50, null=True, verbose_name='Version')),
                ('host_id', models.CharField(max_length=100, verbose_name='HostID')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='过期时间')),
                ('remaining_days', models.IntegerField(default=0, verbose_name='剩余天数')),
                ('quantity', models.IntegerField(default=1, verbose_name='授权数量')),
                ('status', models.IntegerField(choices=[(1, '有效'), (2, '已过期'), (3, '即将到期'), (0, '已撤销')], default=0, verbose_name='状态')),
                ('extra_info', models.JSONField(blank=True, null=True, verbose_name='额外信息')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='lylicense.licenseapplication', verbose_name='关联申请')),
            ],
            options={
                'verbose_name': 'License记录',
                'verbose_name_plural': 'License记录',
                'db_table': 'lylicense_record',
                'ordering': ['-create_datetime'],
            },
        ),
        migrations.CreateModel(
            name='LicenseFieldMapping',
            fields=[
                ('id', models.CharField(default=utils.models.make_uuid, help_text='Id', max_length=100, primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=100, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=100, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=100, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('license_type', models.CharField(choices=[('bitanswer', 'Bitanswer'), ('flexnet', 'FlexNet')], max_length=20, verbose_name='License类型')),
                ('user_type', models.CharField(choices=[('internal', '内部'), ('external', '外部')], max_length=20, verbose_name='用户类型')),
                ('field_type', models.CharField(choices=[('feature', 'Feature'), ('customer_info', 'CustomerInfo'), ('applicant_info', 'ApplicantInfo'), ('common', 'Common')], default='common', max_length=20, verbose_name='字段类型')),
                ('field', models.CharField(max_length=100, verbose_name='原始字段名')),
                ('name', models.CharField(max_length=200, verbose_name='字段含义')),
                ('real_key', models.CharField(max_length=100, verbose_name='映射后的真实key')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否废弃')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': 'License字段映射',
                'verbose_name_plural': 'License字段映射',
                'db_table': 'lylicense_field_mapping',
                'ordering': ['license_type', 'user_type', 'field_type', 'field'],
                'unique_together': {('license_type', 'user_type', 'field')},
            },
        ),
    ]
