# Generated by Django 4.2.30 on 2026-06-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lylicense', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensefieldmapping',
            name='third_party_feature_id',
            field=models.IntegerField(blank=True, help_text="第三方平台（如Bitanswer）上的Feature唯一标识ID，仅当field_type为'feature'时使用", null=True, verbose_name='第三方平台FeatureID'),
        ),
    ]
