# Generated by Django 4.2.30 on 2026-07-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lylicense', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenseapplication',
            name='scope_application',
            field=models.CharField(blank=True, help_text='内部申请时的具体使用场景：客户现场使用、需要IT安装到公司服务器等', max_length=100, null=True, verbose_name='使用范围具体值'),
        ),
        migrations.AddField(
            model_name='licenseapplication',
            name='usage_type',
            field=models.CharField(blank=True, choices=[('internal', '内部'), ('external', '外部')], default='external', help_text='内部:公司内部测试使用、客户现场使用、需要IT安装到公司服务器；外部:其他', max_length=20, null=True, verbose_name='使用范围'),
        ),
    ]
