# Generated by Django 4.1.8 on 2026-05-20 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lylicense', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensefieldmapping',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
