# Generated by Django 4.1.8 on 2026-05-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lylicense', '0002_alter_licensefieldmapping_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenseapplication',
            name='hostname',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='主机名'),
        ),
        migrations.AddField(
            model_name='licenseapplication',
            name='product',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='产品名称'),
        ),
        migrations.AddField(
            model_name='licenseapplication',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='序列号'),
        ),
    ]
