# Generated by Django 4.1.8 on 2026-05-21 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lylicense', '0003_licenseapplication_hostname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenseapplication',
            name='feature',
            field=models.JSONField(blank=True, null=True, verbose_name='Feature列表'),
        ),
    ]
