# Generated by Django 4.1.8 on 2026-05-21 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lylicense', '0004_alter_licenseapplication_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenseapplication',
            name='quantity',
            field=models.JSONField(blank=True, null=True, verbose_name='授权数量'),
        ),
    ]
