# Generated by Django 4.1.8 on 2026-05-21 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lylicense', '0005_alter_licenseapplication_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licensefieldmapping',
            name='dept_belong_id',
        ),
        migrations.AddField(
            model_name='licensefieldmapping',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
    ]
