# Generated by Django 4.1.8 on 2026-05-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lylicense', '0006_remove_licensefieldmapping_dept_belong_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenseapplication',
            name='keyword',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='关键字/匹配标识'),
        ),
    ]
