# Generated by Django 4.1.8 on 2026-05-22 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lylicense', '0007_licenseapplication_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenserecord',
            name='end_date_str',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='过期日期(格式化)'),
        ),
        migrations.AddField(
            model_name='licenserecord',
            name='start_date_str',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='开始日期(格式化)'),
        ),
    ]
