# Generated by Django 4.1.8 on 2026-05-22 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lylicense', '0008_licenserecord_end_date_str_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenseapplication',
            name='end_time',
            field=models.DateField(blank=True, null=True, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='licenseapplication',
            name='start_time',
            field=models.DateField(blank=True, null=True, verbose_name='开始时间'),
        ),
    ]
