# Generated by Django 4.1.8 on 2026-05-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lylicense', '0009_alter_licenseapplication_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenserecord',
            name='end_time',
            field=models.DateField(verbose_name='过期时间'),
        ),
        migrations.AlterField(
            model_name='licenserecord',
            name='start_time',
            field=models.DateField(verbose_name='开始时间'),
        ),
    ]
