# Generated by Django 4.1.8 on 2026-05-26 13:50

from django.db import migrations, models


def clean_duplicate_serial_numbers(apps, schema_editor):
    """
    清理重复的serial_number数据
    保留最新的记录，将其他重复记录的serial_number设置为None
    """
    LicenseApplication = apps.get_model('lylicense', 'LicenseApplication')
    
    # 查找所有有serial_number的记录
    applications = LicenseApplication.objects.filter(
        serial_number__isnull=False
    ).exclude(
        serial_number=''
    ).order_by('-create_datetime')
    
    seen_serials = set()
    duplicates_count = 0
    
    for app in applications:
        if app.serial_number in seen_serials:
            # 这是重复的，清空serial_number
            app.serial_number = None
            app.save(update_fields=['serial_number'])
            duplicates_count += 1
        else:
            seen_serials.add(app.serial_number)
    
    if duplicates_count > 0:
        print(f"清理了 {duplicates_count} 条重复的序列号记录")


class Migration(migrations.Migration):

    dependencies = [
        ('lylicense', '0010_alter_licenserecord_end_time_and_more'),
    ]

    operations = [
        # 先清理重复数据
        migrations.RunPython(clean_duplicate_serial_numbers, migrations.RunPython.noop),
        # 再添加唯一约束
        migrations.AlterField(
            model_name='licenseapplication',
            name='serial_number',
            field=models.CharField(blank=True, help_text='每个申请的唯序列号，用于防止重复申请', max_length=100, null=True, unique=True, verbose_name='申请序列号'),
        ),
    ]
