# Generated by Django 4.1.8 on 2026-05-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lylicense', '0011_alter_licenseapplication_serial_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='licensefieldmapping',
            options={'ordering': ['license_type', 'user_type', 'product', 'field_type', 'field'], 'verbose_name': 'License字段映射', 'verbose_name_plural': 'License字段映射'},
        ),
        migrations.AddField(
            model_name='licensefieldmapping',
            name='product',
            field=models.CharField(blank=True, help_text='用于将相同产品的feature归类，如 GloryEX、GloryBolt', max_length=100, null=True, verbose_name='产品名称'),
        ),
    ]
