# Generated by Django 4.1.8 on 2026-05-28 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lylicense', '0012_alter_licensefieldmapping_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenseapplication',
            name='serial_number',
            field=models.CharField(blank=True, help_text='申请序列号，允许多个产品共享同一序列号', max_length=100, null=True, verbose_name='申请序列号'),
        ),
    ]
