# Generated by Django 4.1.8 on 2026-05-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lylicense', '0013_alter_licenseapplication_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenseapplication',
            name='file_hash',
            field=models.CharField(blank=True, help_text='文件内容的MD5哈希，用于防止相同文件重复处理', max_length=64, null=True, unique=True, verbose_name='文件哈希值'),
        ),
    ]
