# Generated by Django 4.1.8 on 2026-05-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lylicense', '0014_licenseapplication_file_hash'),
    ]

    operations = [
        # 移除 file_hash 字段的 unique 约束
        migrations.AlterField(
            model_name='licenseapplication',
            name='file_hash',
            field=models.CharField(blank=True, help_text='文件内容的MD5哈希，用于防止相同文件重复处理', max_length=64, null=True, verbose_name='文件哈希值'),
        ),
        # 添加联合唯一约束：file_hash + product
        migrations.AlterUniqueTogether(
            name='licenseapplication',
            unique_together={('file_hash', 'product')},
        ),
    ]
