# Generated by Django 4.1.8 on 2026-05-19 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mysystem', '0002_alter_users_identity_alter_users_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowInstance',
            fields=[
                ('id', models.CharField(default=utils.models.make_uuid, help_text='Id', max_length=100, primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=100, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=100, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=100, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('instance_no', models.CharField(max_length=50, unique=True, verbose_name='流程编号')),
                ('title', models.CharField(max_length=200, verbose_name='流程标题')),
                ('status', models.SmallIntegerField(choices=[(0, '草稿'), (1, '审批中'), (2, '已通过'), (3, '已驳回'), (4, '已撤回'), (5, '已取消')], default=0, verbose_name='流程状态')),
                ('current_step', models.IntegerField(default=1, verbose_name='当前步骤')),
                ('total_steps', models.IntegerField(default=0, verbose_name='总步骤数')),
                ('form_data', models.JSONField(blank=True, null=True, verbose_name='表单数据')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_instances', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
                ('applicant_dept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mysystem.dept', verbose_name='申请部门')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '流程实例',
                'verbose_name_plural': '流程实例',
                'db_table': 'lyworkflow_instance',
                'ordering': ('-create_datetime',),
            },
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.CharField(default=utils.models.make_uuid, help_text='Id', max_length=100, primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=100, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=100, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=100, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('step_name', models.CharField(max_length=100, verbose_name='步骤名称')),
                ('step_order', models.IntegerField(verbose_name='步骤顺序')),
                ('approver_type', models.SmallIntegerField(choices=[(1, '指定角色'), (2, '指定部门'), (3, '部门负责人'), (4, '指定人员')], verbose_name='审批人类型')),
                ('allow_return', models.BooleanField(default=True, verbose_name='是否允许退回')),
                ('allow_reject', models.BooleanField(default=False, verbose_name='是否允许驳回（直接结束）')),
                ('approver_dept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mysystem.dept', verbose_name='审批部门')),
                ('approver_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mysystem.role', verbose_name='审批角色')),
                ('approver_users', models.ManyToManyField(blank=True, related_name='approved_workflow_steps', to=settings.AUTH_USER_MODEL, verbose_name='审批人员')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '流程步骤',
                'verbose_name_plural': '流程步骤',
                'db_table': 'lyworkflow_step',
                'ordering': ('step_order',),
            },
        ),
        migrations.CreateModel(
            name='WorkflowType',
            fields=[
                ('id', models.CharField(default=utils.models.make_uuid, help_text='Id', max_length=100, primary_key=True, serialize=False, verbose_name='Id')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=100, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=100, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('name', models.CharField(max_length=100, verbose_name='流程名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='流程编码')),
                ('description', models.TextField(blank=True, null=True, verbose_name='流程描述')),
                ('icon', models.CharField(blank=True, max_length=100, null=True, verbose_name='图标')),
                ('status', models.SmallIntegerField(default=1, verbose_name='状态（0禁用/1启用）')),
                ('sort', models.IntegerField(default=1, verbose_name='排序')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '流程类型',
                'verbose_name_plural': '流程类型',
                'db_table': 'lyworkflow_type',
                'ordering': ('sort',),
            },
        ),
        migrations.CreateModel(
            name='WorkflowTask',
            fields=[
                ('id', models.CharField(default=utils.models.make_uuid, help_text='Id', max_length=100, primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=100, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=100, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=100, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('step_order', models.IntegerField(verbose_name='步骤顺序')),
                ('status', models.SmallIntegerField(choices=[(0, '待审批'), (1, '已通过'), (2, '已驳回'), (3, '已退回')], default=0, verbose_name='任务状态')),
                ('approve_result', models.SmallIntegerField(choices=[(0, '未审批'), (1, '通过'), (2, '驳回'), (3, '退回')], default=0, verbose_name='审批结果')),
                ('approve_comment', models.TextField(blank=True, null=True, verbose_name='审批意见')),
                ('approve_time', models.DateTimeField(blank=True, null=True, verbose_name='审批时间')),
                ('is_cc', models.BooleanField(default=False, verbose_name='是否抄送人员')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_tasks', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='lyworkflow.workflowinstance', verbose_name='流程实例')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lyworkflow.workflowstep', verbose_name='流程步骤')),
            ],
            options={
                'verbose_name': '审批任务',
                'verbose_name_plural': '审批任务',
                'db_table': 'lyworkflow_task',
                'ordering': ('step_order', 'create_datetime'),
            },
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='workflow_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='lyworkflow.workflowtype', verbose_name='流程类型'),
        ),
        migrations.CreateModel(
            name='WorkflowLog',
            fields=[
                ('id', models.CharField(default=utils.models.make_uuid, help_text='Id', max_length=100, primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=100, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=100, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=100, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('action', models.CharField(max_length=50, verbose_name='操作类型')),
                ('action_desc', models.CharField(max_length=200, verbose_name='操作描述')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='lyworkflow.workflowinstance', verbose_name='流程实例')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '流程操作日志',
                'verbose_name_plural': '流程操作日志',
                'db_table': 'lyworkflow_log',
                'ordering': ('-create_datetime',),
            },
        ),
        migrations.AddField(
            model_name='workflowinstance',
            name='workflow_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lyworkflow.workflowtype', verbose_name='流程类型'),
        ),
        migrations.CreateModel(
            name='WorkflowCCInstance',
            fields=[
                ('id', models.CharField(default=utils.models.make_uuid, help_text='Id', max_length=100, primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=100, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=100, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=100, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('notify_time', models.DateTimeField(auto_now_add=True, verbose_name='通知时间')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('cc_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_cc_instances', to=settings.AUTH_USER_MODEL, verbose_name='抄送人员')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cc_instances', to='lyworkflow.workflowinstance', verbose_name='流程实例')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lyworkflow.workflowstep', verbose_name='关联步骤')),
            ],
            options={
                'verbose_name': '流程抄送实例',
                'verbose_name_plural': '流程抄送实例',
                'db_table': 'lyworkflow_cc_instance',
                'ordering': ('-notify_time',),
            },
        ),
        migrations.CreateModel(
            name='WorkflowCC',
            fields=[
                ('id', models.CharField(default=utils.models.make_uuid, help_text='Id', max_length=100, primary_key=True, serialize=False, verbose_name='Id')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=100, null=True, verbose_name='描述')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=100, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=100, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('cc_type', models.SmallIntegerField(choices=[(1, '指定角色'), (2, '指定部门'), (3, '部门负责人'), (4, '指定人员')], verbose_name='抄送人类型')),
                ('can_approve', models.BooleanField(default=True, verbose_name='是否可审批')),
                ('cc_dept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mysystem.dept', verbose_name='抄送部门')),
                ('cc_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mysystem.role', verbose_name='抄送角色')),
                ('cc_users', models.ManyToManyField(blank=True, related_name='cc_workflow_configs', to=settings.AUTH_USER_MODEL, verbose_name='抄送人员')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lyworkflow.workflowstep', verbose_name='关联步骤（为空表示全局抄送）')),
                ('workflow_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cc_configs', to='lyworkflow.workflowtype', verbose_name='流程类型')),
            ],
            options={
                'verbose_name': '流程抄送配置',
                'verbose_name_plural': '流程抄送配置',
                'db_table': 'lyworkflow_cc',
            },
        ),
    ]
