# Generated by Django 4.2.30 on 2026-07-21 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyworkflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstep',
            name='internal_conditions',
            field=models.JSONField(blank=True, help_text='当需要条件化审批人时使用，存储条件与审批人配置的映射。格式: [{condition_group, condition_relation, conditions, approvers_config}]', null=True, verbose_name='节点内部条件配置'),
        ),
    ]
