# Generated by Django 4.2.30 on 2026-08-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyworkflow', '0002_workflowstep_internal_conditions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowcc',
            name='cc_dept',
            field=models.JSONField(blank=True, help_text='存储部门ID列表，如 [1, 2] 或单个ID', null=True, verbose_name='抄送部门'),
        ),
        migrations.AlterField(
            model_name='workflowstep',
            name='approver_dept',
            field=models.JSONField(blank=True, help_text='存储部门ID列表，如 [1, 2] 或单个ID', null=True, verbose_name='审批部门'),
        ),
    ]
