# Generated by Django 4.2.30 on 2026-08-03 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysystem', '0002_alter_users_identity_alter_users_mobile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lyworkflow', '0003_alter_workflowcc_cc_dept_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstep',
            name='cc_dept',
            field=models.JSONField(blank=True, help_text='存储部门ID列表', null=True, verbose_name='抄送部门'),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='cc_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cc_workflow_steps', to='mysystem.role', verbose_name='抄送角色'),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='cc_type',
            field=models.SmallIntegerField(blank=True, help_text='1=指定角色,2=指定部门,3=部门负责人,4=指定人员,5=发起人', null=True, verbose_name='抄送人类型'),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='cc_users',
            field=models.ManyToManyField(blank=True, related_name='cc_workflow_steps', to=settings.AUTH_USER_MODEL, verbose_name='抄送人员'),
        ),
        migrations.AlterField(
            model_name='workflowcc',
            name='cc_type',
            field=models.SmallIntegerField(choices=[(1, '指定角色'), (2, '指定部门'), (3, '部门负责人'), (4, '指定人员'), (5, '发起人')], verbose_name='抄送人类型'),
        ),
        migrations.AlterField(
            model_name='workflowstep',
            name='approver_type',
            field=models.SmallIntegerField(choices=[(1, '指定角色'), (2, '指定部门'), (3, '部门负责人'), (4, '指定人员'), (5, '申请人自选'), (6, '多级审批（组合）'), (7, '发起人')], verbose_name='审批人类型'),
        ),
    ]
