# Generated by Django 4.2.30 on 2026-08-03 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyworkflow', '0004_workflowstep_cc_dept_workflowstep_cc_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstep',
            name='product_line',
            field=models.CharField(blank=True, help_text='标识该节点所属的产品线，如 RC、EMIR&Grid、STA、Phybolt', max_length=100, null=True, verbose_name='产品线'),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='product_line_cc_rules',
            field=models.JSONField(blank=True, help_text='当approver_type=7（发起人）时使用，根据已完成的产品线节点确定抄送人。格式: [{product_line, cc_type, cc_role, cc_dept, cc_users}]', null=True, verbose_name='产品线抄送规则'),
        ),
    ]
