# Generated by Django 4.1.8 on 2026-08-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyworkflow', '0005_workflowstep_product_line_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowtype',
            name='allowed_initiator_depts',
            field=models.JSONField(blank=True, help_text='存储部门ID列表，如 [1, 2]。为空或不配置表示所有部门均可发起', null=True, verbose_name='允许发起的部门'),
        ),
    ]
