# Generated by Django 4.2.30 on 2026-08-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyworkflow', '0006_workflowtype_allowed_initiator_depts'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstep',
            name='skip_approval_config',
            field=models.JSONField(blank=True, help_text='当发起人满足条件时自动跳过审批。格式: {enabled, skip_conditions: {is_dept_owner, specified_users, specified_roles}, target_step_id}', null=True, verbose_name='自动跳过审批配置'),
        ),
    ]
