# Generated by Django 4.1.8 on 2026-08-04 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyworkflow', '0007_workflowstep_skip_approval_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowstep',
            name='approver_type',
            field=models.SmallIntegerField(choices=[(1, '指定角色'), (2, '指定部门'), (3, '部门负责人'), (4, '指定人员'), (5, '申请人自选'), (6, '多级审批（组合）'), (7, '发起人'), (8, '条件化审批人')], verbose_name='审批人类型'),
        ),
    ]
