# Generated by Django 4.1.8 on 2026-08-05 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utils.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lyworkflow', '0008_alter_workflowstep_approver_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowstep',
            name='approver_type',
            field=models.SmallIntegerField(choices=[(1, '指定角色'), (2, '指定部门'), (3, '部门负责人'), (4, '指定人员'), (5, '申请人自选'), (6, '多级审批（组合）'), (7, '发起人'), (8, '条件化审批人'), (10, '自定义审批组')], verbose_name='审批人类型'),
        ),
        migrations.CreateModel(
            name='ApprovalGroup',
            fields=[
                ('id', models.CharField(default=utils.models.make_uuid, help_text='Id', max_length=100, primary_key=True, serialize=False, verbose_name='Id')),
                ('modifier', models.CharField(blank=True, help_text='修改人', max_length=100, null=True, verbose_name='修改人')),
                ('dept_belong_id', models.CharField(blank=True, help_text='数据归属部门', max_length=100, null=True, verbose_name='数据归属部门')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('name', models.CharField(max_length=100, verbose_name='审批组名称')),
                ('product_line', models.CharField(blank=True, help_text='该审批组对应的产品线标识，如 RC、EMIR&Grid、STA、Phybolt', max_length=100, null=True, verbose_name='产品线')),
                ('description', models.TextField(blank=True, null=True, verbose_name='审批组说明')),
                ('creator', models.ForeignKey(db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('members', models.ManyToManyField(blank=True, related_name='approval_groups', to=settings.AUTH_USER_MODEL, verbose_name='组成员')),
            ],
            options={
                'verbose_name': '自定义审批组',
                'verbose_name_plural': '自定义审批组',
                'db_table': 'lyworkflow_approval_group',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='approver_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_steps', to='lyworkflow.approvalgroup', verbose_name='审批组'),
        ),
    ]
