# Generated by Django 4.1.8 on 2026-08-05 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lyworkflow', '0009_alter_workflowstep_approver_type_approvalgroup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowcc',
            name='cc_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cc_configs', to='lyworkflow.approvalgroup', verbose_name='抄送审批组'),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='cc_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cc_steps', to='lyworkflow.approvalgroup', verbose_name='抄送审批组'),
        ),
        migrations.AlterField(
            model_name='workflowcc',
            name='cc_type',
            field=models.SmallIntegerField(choices=[(1, '指定角色'), (2, '指定部门'), (3, '部门负责人'), (4, '指定人员'), (5, '发起人'), (6, '自定义审批组')], verbose_name='抄送人类型'),
        ),
        migrations.AlterField(
            model_name='workflowstep',
            name='cc_type',
            field=models.SmallIntegerField(blank=True, help_text='1=指定角色,2=指定部门,3=部门负责人,4=指定人员,5=发起人,6=自定义审批组', null=True, verbose_name='抄送人类型'),
        ),
        migrations.AlterField(
            model_name='workflowstep',
            name='product_line_cc_rules',
            field=models.JSONField(blank=True, help_text='当approver_type=7（发起人）时使用，根据已完成的产品线节点确定抄送人。格式: [{product_line, cc_type, cc_role, cc_dept, cc_users, cc_group}]，cc_type=6时使用cc_group引用自定义审批组', null=True, verbose_name='产品线抄送规则'),
        ),
    ]
