# Generated by Django 4.1.8 on 2026-08-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyworkflow', '0010_workflowcc_cc_group_workflowstep_cc_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowinstance',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '草稿'), (1, '审批中'), (2, '已通过'), (3, '已驳回'), (4, '已撤回'), (5, '已取消'), (6, '已退回')], default=0, verbose_name='流程状态'),
        ),
    ]
