# Generated by Django 4.1.8 on 2026-08-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyworkflow', '0011_alter_workflowinstance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowinstance',
            name='submit_round',
            field=models.IntegerField(default=0, verbose_name='提交轮次'),
        ),
        migrations.AddField(
            model_name='workflowtask',
            name='round',
            field=models.IntegerField(default=0, verbose_name='提交轮次'),
        ),
    ]
