# -*- coding: utf-8 -*-
# Generated by Django 3.2.25 on 2026-08-18
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyworkflow', '0013_workflowcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowcomment',
            name='attachments',
            field=models.JSONField(blank=True, help_text='附件信息列表：[{"name": "原始文件名", "path": "相对media路径", "size": "文件大小"}]', null=True, verbose_name='附件列表'),
        ),
    ]
